---
title: 'Aplicación del paquete estadístico R para la visualización y el análisis de datos pesqueros y ecológicos'
subtitle: 'Unidad Académica Mazatlán'
author: 
- Matias Braccini
- Department of Primary Industries and Regional Development of Western Australia
date: "7-11 October 2019"
output: 
    powerpoint_presentation:
      reference_doc: 'C:/Matias/Cursos/2019_Mexico/Style.pptx'
      slide_level: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Acknowledgements
Big thanks to Simon De Lestang, John Hoenig, Ainslie Denham and Alex Hesp for providing with reference code and material 

## Introduction
- R is a system for statistical analyses and graphics created by Ross Ihaka and Robert Gentleman <br>
(*Ihaka R. & Gentleman R. 1996. R: a language for data analysis and graphics. Journal of Computational and Graphical Statistics 5: 299–314*)
- Freely distributed and open-source, allowing for users to change and improve the software
- development and distribution are carried out by several statisticians known as the R Development Core Team
- R is available in several forms (Windows, Linux, Macintosh, etc)
- There are 'default packages' and there are additional packages that have to be installed and loaded
- When R is running, variables, data, functions, results, etc, are stored in
the active memory of the computer in the form of objects which have a name

## R is an “object-oriented” programming language (like Python, JavaScript).
- what's an “object”?
-  an object is anything I assign values to (e.g. x <- 5; y<-"hi")
- objects are boxes in which one can put things: data, functions, other objects...

## Rstudio
- Rstudio is an IDE (Integrated development environment) for R
- It includes a console, text editor, tools for plotting, history, debugging, etc

## What we will do this week
- R basics (vectors, matrices, lists and data frames)
- General statistics
- Data manipulations
- 


## Let's get started.......
